// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqexwxhijstzeloymobu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxZXh3eGhpanN0emVsb3ltb2J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NDA1NDEsImV4cCI6MjA1MDUxNjU0MX0.bFpdBC7GmFbAiwzr8wzhHEl6gl2WTXAxNfoqCDSi7Vk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);